name: OWASP Dependency Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  owasp-dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11' # Specify the Java version

      - name: Run OWASP Dependency Check
        uses: jeremylong/DependencyCheck@v6.7.0
        with:
          format: 'ALL' # Output formats: XML, JSON, CSV, HTML
          output-directory: 'dependency-check-report'
          scan: '.' # Specify the path to scan

      - name: Upload Dependency-Check Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: dependency-check-report

