name: OWASP Dependency Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  owasp-dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11' # Specify the Java version
          distribution: 'temurin' # Specify the Java distribution

      - name: Install OWASP Dependency Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.0.2/dependency-check-8.0.2-release.zip
          unzip dependency-check-8.0.2-release.zip
          ls -l
          ls -l dependency-check
          ls -l dependency-check/bin
          sudo mv dependency-check/bin/dependency-check /usr/local/bin/

      - name: Run OWASP Dependency Check
        run: |
          dependency-check --project my-project --scan . --format ALL --out dependency-check-report

      - name: Upload Dependency-Check Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: dependency-check-report




