name: build
on:
  push:
    branches: [ "master" ]
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'
          
      - name: Install JFrog CLI
        run: curl -fL https://getcli.jfrog.io | sh

      - name: Configure JFrog CLI
        env:
          JFROG_CLI_HOME: ${{ runner.temp }}
          JFROG_CLI_JFROG_URL: ${{ secrets.JFROG_URL }}  # URL of your JFrog Artifactory
          JFROG_CLI_JFROG_USER: ${{ secrets.ARTIFACTORY_USER }}  # Your JFrog username
          JFROG_CLI_JFROG_PASSWORD: ${{ secrets.ARTIFACTORY_API_KEY }}  # Your JFrog password
        run: |
          jfrog config add my-artifactory \
            --url=$JFROG_CLI_JFROG_URL \
            --user=$JFROG_CLI_JFROG_USER \
            --password=$JFROG_CLI_JFROG_PASSWORD

      - name: Upload Trivy results to JFrog Artifactory
        env:
          JFROG_CLI_HOME: ${{ runner.temp }}
        run: |
          jfrog rt upload "trivy-results.sarif" "/trivy-results.sarif"
