name: Trivy Scan

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Run Trivy Scan
        run: |
          mkdir -p trivy-results
          trivy fs --format json --output trivy-results/scan-results.json .
